### ISSUE TITLE
Error on merge

### ISSUE THREAD

**Issue by Andrer757** [Simdea/gmlrva#2]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@label value=(@string/app_name) from AndroidManifest.xml:9:9-41
  	is also present at [pt.simdea:gmlrva.lib:1.3] AndroidManifest.xml:12:9-48 value=(@string/gmlrva_app_name).
  	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:5:5-22:19 to override.

**Comment by paribeiro10** [comment]
Fixed in version [1.4](https://github.com/Simdea/gmlrva/releases/tag/1.4).
