### ISSUE TITLE
Add Generic Item Decoration

### ISSUE THREAD

**Issue by Andrer757** [Simdea/gmlrva#8]

**Comment by paribeiro10** [comment]
Issue scope is not clearly defined.
Redefining scope to the addition of a base architecture for adding [RecyclerView Item Decorations](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.ItemDecoration.html).

**Comment by paribeiro10** [comment]
Added a base architecture for adding [RecyclerView Item Decorations](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.ItemDecoration.html).

I will close this issue since further decoration additions should associate their own issue and pull request.
